### PR TITLE
Doc updates

### PR DESCRIPTION
**Pull request by bjones1**
All,

I've revised the block diagram based on our discussion last week, and added some preliminary docs. Given this PR involving deleting files from @cueltschey, I'd appreciate his review (and anyone else who has time) before merging.

### CODE REVIEW

**Review by cueltschey — APPROVED** [review]
These changes look great to me. Thanks.

**Comment by bjones1** [comment]
Thanks for the quick feedback! I'll wait a bit to see if @joshuamoorexyz or @Higgigamer19 have any thoughts.

**Comment by joshuamoorexyz** [comment]
Looks good. 

+ The RU emulator should not be public as the intended solution is primarily targeted at SDR/RU based deployments.
+ The figure from Graphviz is nice. It features Grafana which i believe we intend to replace and 'scappy' is only for supporting the fuzzing tests so im not sure it should be here in a general diagram. Is there any way to explicitly define the order in this figure which would be helpful?

**Comment by joshuamoorexyz** [comment]
There are some Docs in the main repo which should either be moved to docs or deleted if they have been updated and moved already.

**Comment by bjones1** [comment]
> * The RU emulator should not be public as the intended solution is primarily targeted at SDR/RU based deployments.

Should we therefore move `docs\ru_emulation.md` to another repo? If so, which one?

**Comment by joshuamoorexyz** [comment]
> > * The RU emulator should not be public as the intended solution is primarily targeted at SDR/RU based deployments.
> 
> Should we therefore move `docs\ru_emulation.md` to another repo? If so, which one?

I made a new Repo containing the synced srsRAN Project files that is private and included the RU Emulation docs in the relevant folder. I have thus deleted the Ru emulation docs from the soft t UE repo entirely. Let me know what you think of this solution.

**Comment by bjones1** [comment]
> * The figure from Graphviz is nice. It features Grafana which i believe we intend to replace and 'scappy' is only for supporting the fuzzing tests so im not sure it should be here in a general diagram. Is there any way to explicitly define the order in this figure which would be helpful?

Here's a few preliminary edits. By order, do you mean the left-to-right ordering of subprocesses? If so, I can't find a nice way of oing this. Here's some edits -- hopefully, we can do this here in GitHub then copy/paste back to the repo when this looks good. Just look at the source of this comment.

 tue
        client -> pcap [ dir=both ]
        client -> grafana_gnb
        client -> grafana_5gc
        client -> iperf3 [ dir = both ]
        client [ label = "Client GUI\n(Python)"]
        tue [ label = "Soft T-UE"]
        pcap [ label = "Packet capture"]
        grafana_gnb [ label = "Grafana gNodeB\ndata viz"]
        grafana_5gc [ label = "Grafana open 5G core\ndata viz"]
        iperf3 [ label = "iperf3\nclient"]
    }
    client -> server [ dir = both, style = dotted ]
    tue -> gnb [ dir = both, style = dotted ]
    gnb -> grafana_gnb [ style = dotted ]
    open5g -> grafana_5gc [ style = dotted ]
    iperf3 -> iperf3_server [ dir = both, style = dotted ]
    subgraph cluster_server {
        label = "Server PC"
        server -> iperf3_server
        server -> gnb
        gnb -> open5g [ style = dotted ]
        server [ label = "Server\n(Python)"]
        gnb [ label = "gNodeB"]
        open5g [ label = "Open5G\nCore"]
        iperf3_server [ label = "iperf3\nserver"]
    }
})'/>

**Comment by bjones1** [comment]
Never mind -- it looks like that doesn't work, sigh. Here's the image. All I did was remove scapy.

graph

**Review by joshuamoorexyz — APPROVED** [review]

**Comment by joshuamoorexyz** [comment]
Looks fine to me now then. We can merge if no other blockers.

**Comment by bjones1** [comment]
> I made a new Repo containing the synced srsRAN Project files that is private and included the RU Emulation docs in the relevant folder. I have thus deleted the Ru emulation docs from the soft t UE repo entirely. Let me know what you think of this solution.

Perfect!

**Pull request merged**
