### PR TITLE
all655: update scripts and add to CI/CD

### PR DESCRIPTION
**Pull request by cueltschey**
Leal updated all our install scripts to be more efficient and reliable. He has also documented and tested them well.

I made sure that the scripts work well with our existing CI/CD

### CODE REVIEW

**Comment by bjones1** [comment]
@cueltschey, I see you closed this -- should I review it? Have you merged it elsewhere?

**Comment by cueltschey** [comment]
Yes sorry, I closed it since lael was not ready.

**Comment by cueltschey** [comment]
Feel free to comment, I think that would be helpful

**Comment by all655** [comment]
@bjones1 I have more changes to make first. Thank you.

**Comment by bjones1** [comment]
Sounds good. Let me know when you're ready for my review (comment here or message me on Teams).

**Pull request closed without merging**
